import { StyleSheet, Dimensions } from 'react-native';

const { height, width } = Dimensions.get('window');

// Splash Screen
const SPLASH_BACKGROUND_COLOR = '#FFFFFF';
const SPLASH_TITLE_FONT_SIZE = 0.05 * height;
const SPLASH_TITLE_COLOR = '#001815';
const SPLASH_LOGO_WIDTH = 0.5 * width;
const SPLASH_LOGO_HEIGHT = 0.2 * height;

// Onboarding Screen
const ONBOARDING_BACKGROUND_COLOR = '#1E1E1E';
const ONBOARDING_TITLE_FONT_SIZE = 0.04 * height;
const ONBOARDING_TITLE_COLOR = '#FFFFFF';
const ONBOARDING_SUBTITLE_FONT_SIZE = 0.03 * height;
const ONBOARDING_SUBTITLE_COLOR = '#B9C1BE';
const ONBOARDING_BUTTON_COLOR = '#FFFFFF';
const ONBOARDING_BUTTON_TEXT_COLOR = '000E08';
const ONBOARDING_OR_COLOR = "#D6E4E0";
const ONBOARDING_RULER_COLOR = "#CDD1D0";

// Sign in and Sign up
const SIGNIN_BACKGROUND_COLOR = '#FFFFFF';
const SIGNIN_TITLE_FONT_SIZE = 0.04 * height;
const SIGNIN_TITLE_COLOR = '#000E08';
const SIGNIN_OR_COLOR = "#797C7B";
const SIGNIN_RULER_COLOR = "#CDD1D0";
const SIGNIN_TEXT_COLOR = "#24786D";
const SIGNIN_BUTTON_COLOR = '#F3F6F6';
const SIGNIN_BUTTON_TEXT_COLOR = '#797C7B';
const SIGNIN1_BUTTON_COLOR = '#24786D';
const SIGNIN1_BUTTON_TEXT_COLOR = '#FFFFFF';

// Input Fields
const INPUT_HEIGHT = 0.075 * height;
const INPUT_WIDTH = 0.8 * width;
const INPUT_BORDER_RADIUS = 0.012 * height;
const INPUT_BORDER_COLOR = '#CDD1D0';
const INPUT_FONT_SIZE = 0.022 * height;
const INPUT_TEXT_COLOR = "#000E08";
const INPUT_BACKGROUND_COLOR = '#FFFFFF';

// General
const ICON_WIDTH = 0.6 * width;
const ICON_HEIGHT = 0.3 * height;
const TEXT_FONT_SIZE = 0.02 * height;
const TEXT_FONT_COLOR = "#B9C1BE";
const ERROR_COLOR = "#FF2D1B";
const ERROR_FONT_SIZE = 0.02 * height;
const BUTTON_HEIGHT = 0.06 * height;
const BUTTON_WIDTH = 0.85 * width;
const BUTTON_BORDER_RADIUS = 0.018 * height;
const BUTTON_FONT_SIZE = 0.02 * height;

const GlobalStyles = {
    SPLASH_BACKGROUND_COLOR,
    SPLASH_TITLE_FONT_SIZE,
    SPLASH_TITLE_COLOR,
    SPLASH_LOGO_WIDTH,
    SPLASH_LOGO_HEIGHT,
    ONBOARDING_BACKGROUND_COLOR,
    ONBOARDING_TITLE_FONT_SIZE,
    ONBOARDING_TITLE_COLOR,
    ONBOARDING_SUBTITLE_FONT_SIZE,
    ONBOARDING_SUBTITLE_COLOR,
    ONBOARDING_BUTTON_COLOR,
    ONBOARDING_BUTTON_TEXT_COLOR,
    ONBOARDING_OR_COLOR,
    ONBOARDING_RULER_COLOR,
    SIGNIN_BACKGROUND_COLOR,
    SIGNIN_TITLE_FONT_SIZE,
    SIGNIN_TITLE_COLOR,
    SIGNIN_OR_COLOR,
    SIGNIN_RULER_COLOR,
    SIGNIN_TEXT_COLOR,
    SIGNIN_BUTTON_COLOR,
    SIGNIN_BUTTON_TEXT_COLOR,
    SIGNIN1_BUTTON_COLOR,
    SIGNIN1_BUTTON_TEXT_COLOR,
    INPUT_HEIGHT,
    INPUT_WIDTH,
    INPUT_BORDER_RADIUS,
    INPUT_BORDER_COLOR,
    INPUT_FONT_SIZE,
    INPUT_TEXT_COLOR,
    INPUT_BACKGROUND_COLOR,
    ICON_WIDTH,
    ICON_HEIGHT,
    TEXT_FONT_SIZE,
    TEXT_FONT_COLOR,
    ERROR_COLOR,
    ERROR_FONT_SIZE,
    BUTTON_HEIGHT,
    BUTTON_WIDTH,
    BUTTON_BORDER_RADIUS,
    BUTTON_FONT_SIZE
};

export default GlobalStyles;